### ISSUE TITLE
Flashx.TV Stream Quelle brauch "Auth"

### ISSUE THREAD

**Issue by powo01** [lastship/plugin.video.lastship#1]
Hallo Team,

ich habe in den Plugin Einstellungen die Provider die eine "Authentification" benötigen ausgeschaltet. Seit einiger Zeit fragt die flashx Quelle auch nach eine PreAuth. Könnt Ihr bitte flashx als Auth Provider markieren (in sources.py), damit der Suchvorgang wieder ohne Nachfragen geht ?

Vielen Dank,
powo

**Comment by lastship** [comment]
Mit dem Update welches gleich online geht, ist ein fix für flashx drin
