### ISSUE TITLE
VodHD als Premium Quelle anzeigen

### ISSUE THREAD

**Issue by lastship** [lastship/plugin.video.lastship#113]
VodHD wird als Preimium angezeigt (ist in vodhd.py so eingebaut)

ABER wenn man in den LS Einstellungen auf "Nur Premium Quellen anzeigen" einstellt, wird VodHD NICHT mehr als Premium angezeigt

**Comment by Philps** [comment]
wont fix. sollte überlegen "nur premium quellen anzeigen" zu deaktivieren
