### ISSUE TITLE
Wrong Episode playing

### ISSUE THREAD

**Issue by styler2go** [lastship/plugin.video.lastship#121]
Hi, i am trying to Play Episode one of some series and it plays some random episode from some other season.

I tried this with multiple series all and some have the same issue. I tried disabling all index pages except one and it keeps happening. 

Any ideas / anyone else?

**Comment by sraedler** [comment]
Welche Webseite?
Cinematrix?

**Comment by styler2go** [comment]
Kinox

**Comment by sraedler** [comment]
Beispiel Serie, Staffel und Episode 

Je mehr desto besser

**Comment by styler2go** [comment]
Ich hatte es bei The Flash und bei Agents of Shield, Staffel 5 Folge 1

**Comment by sraedler** [comment]
Habt ihr das mit der Webseite verglichen?
Kommen da auch die falschen Episoden?

**Comment by styler2go** [comment]
Auf der Website wird die richtige Folge abgespielt.

Kann man hier irgendwie debuggen Helfen? Gibt es einen Debug-Modus den man aktivieren kann um Logs o.ä. einzusehen?

**Comment by sraedler** [comment]
https://github.com/lastship/FAQ/blob/master/Lastship_FAQ.md#4-fehlerbericht-über-log-datei

Hier gibts eine Anleitung.

Du kannst auch gern selbst etwas einlesen und versuchen.
Es kann immer etwas dauern bis ein Entwickler Zeit hat. Wir sind um jede Hilfe dankbar

**Comment by sraedler** [comment]
@styler2go @nJoy-Android Ich hab tatsächlich einen typo-Fehler gefunden.

Könnt ihr bitte nochmals testen und dann bescheid geben, ob alles klappt?

**Comment by styler2go** [comment]
Über nightly updaten?

**Comment by sraedler** [comment]
ja, jetzt auch in dem normalen
Funktioniert oder?

**Comment by sraedler** [comment]
no response close
