### ISSUE TITLE
prüfen Standartencoding UTF8 vs. iso-8859-1

### ISSUE THREAD

**Issue by Philps** [lastship/plugin.video.lastship#184]
Quellcode ist standartmässig UTF8 encodiert. Überlegung standartmäßig auf iso-8859-1 zu migrieren oder einheitlich zu gestalten.

Weiterführende Infos:
https://www.python-forum.de/viewtopic.php?t=5095
https://mothereff.in/utf-8

**Comment by Erestris** [comment]
Es ist einheitlich auf UTF-8. Eine andere Codierung ist für uns nicht notwendig/sinnvoll. Kann meiner Meinung nach geschlossen werden.
