### ISSUE TITLE
Trakt-Serien-Lists

### ISSUE THREAD

**Issue by xCrashsystemx** [lastship/plugin.video.lastship#19]
Ich habe gerade gesehen das unter Meine Serien bei Trakt die Serien Listen fehlen.
Unter Meine Filme ist sind die Listen  vorhanden.

Desweiteren werden in der Film Liste auch eigene Serien Listen angezeigt, die kann man dort nicht auswählen, weil er sagt "nichts 
gefunden", aber die Film Listen wo nur Filme drin sind funktionieren

Unter Filme -> ![grafik](https://user-images.githubusercontent.com/32362149/41357677-fc528d94-6f26-11e8-888d-1069339ae181.png)

Unter Serien -> 
![grafik](https://user-images.githubusercontent.com/32362149/41357731-16f36c36-6f27-11e8-8cd9-f5c2ec04b25c.png)

**Comment by sraedler** [comment]
Mach bitte im Forum einen Thread auf, hier geht es etwas unter und die Diskussion ist etwas schwieriger.

http://lastship.square7.ch/forum/
