### ISSUE TITLE
lastship board - strange forwarding

### ISSUE THREAD

**Issue by nokodemus** [lastship/plugin.video.lastship#2]
Hi guys 

I've a major problem with our board. Whatever i click on and wherever i'd like to navigate, i'm always being forwarded to: http://lastship.square7.ch/forum/usercp.php?action=email

So i'm always prompted to refresh my e-mail adress ... does anyone else have this issue or an idea how to resolve this?

Thank you ...

**Comment by lastship** [comment]
Wir sind ja ein Deutsches Team, darfst gerene deutsch schreiben -:)
Wird an den Forum Admin weitergeleitet

**Comment by Animizio** [comment]
Dieses Problem ist bereits bekannt.
Du benutzt eine im Nachhinein gesperrte Email Adresse..bitte einfach die Email zu einer anderen ändern und Speicher. Danach ist alles wieder wie vorher. :)

**Comment by nokodemus** [comment]
gesperrte E-Mail-Adresse ?? warum sperrt ihr E-Mail-Adressen ... die E-Mail-Adresse hat doch gepasst?
Und ich hab die E-Mail-Adresse bereits geändert, ohne Erfolg ... derselbe Spaß wie vorher

**Comment by Animizio** [comment]
Das läuft automatisch über den Spam Schutz.Ich schau mir das bei dir Mal an, sollte heute Abend wieder funktionieren. :)
LG Animizio 

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Feb. 21, 2018 at 18:41 schrieb nokodemus<notifications@github.com>:   
gesperrte E-Mail-Adresse ?? warum sperrt ihr E-Mail-Adressen ... die E-Mail-Adresse hat doch gepasst?
Und ich hab die E-Mail-Adresse bereits geändert, ohne Erfolg ... derselbe Spaß wie vorher

**Comment by nokodemus** [comment]
Hab's nun nochmal getestet, nun läuft's :)
Ich meinte das letzte mal vor 3 Tagen, als ich die E-Mail-Addy geändert hatte ... da ging's nicht ... nun läuft die Sache :+1:

**Comment by Animizio** [comment]
Super perfekt :) tut mir leid für die Umstände..

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Feb. 21, 2018 at 18:46 schrieb nokodemus<notifications@github.com>:   
Hab's nun nochmal getestet, nun läuft's :)
Ich meinte das letzte mal vor 3 Tagen, als ich die E-Mail-Addy geändert hatte ... da ging's nicht ... nun läuft die Sache 👍
