### ISSUE TITLE
Findet Serie/Film nicht

### ISSUE THREAD

**Issue by xCrashsystemx** [lastship/plugin.video.lastship#20]
Hallo, mir ist heute ein kleiner "Fehler" aufgefallen und zwar.
Wenn ich z.B. One Piece gucken will (Staffel 17 folge 18 ) findet er nur Streams über Animeloads, obwohl Serienstream z.B. diese Folge Online über den Browser auch hätte. Serienstream Account ist hinterlegt und aktiviert. Das gleiche für Bs.to ( und der Fehler war schon vor 1-2 Monaten wo bs.to noch ging)

Des weiteren wäre mein Vorschlag Seiten wie -&gt; onepiece-tube.com, http://dragonball-tube.com/, naruto-tube.org/ und http://fairytail-tube.org/ etc für den URLResolver hinzufügen die Seiten sind ja vom Aufbau identisch.

**Comment by sraedler** [comment]
Hallo,
Wo siehst du diese Folge Online?
Ich hab es geprüft und das Plugin geht (Staffel 12 Folge 18).

Jedoch auf der Serienstream Seite ist Staffel 17 nicht mal verfügbar.

Die ...-tube seiten werden ziemlich sicher nicht integriert, sofern kein Programmierer sie selber sehen will, da sich der Aufwand für 5-10 Serien nicht rentiert.

**Comment by xCrashsystemx** [comment]
Achso, das liegt daran das Serienstream eine andere Staffel aufteilung hat. Von der Folgen nummer passt es aber. Ich verstehe auch nicht wieso fast jede Seite eine andere Staffel aufteilung hat
