### ISSUE TITLE
Suchfunktion funktioniert nicht (RaspberryPi) 

### ISSUE THREAD

**Issue by lybserv** [lastship/plugin.video.lastship#22]
Hey,

ich bekomme es nicht hin, die Suchfunktion von Lastship auf meinem Raspberry zu nutzen:

"Error getting plugin://plugin.video.lastship/?action=movieSearchterm"
ist das einzige, was währenddessen im Log auftaucht.. 

Unter Linux + Windows funktioniert sie ohne Probleme

**Comment by nokodemus** [comment]
Hier is momentan alles paletti. Sowohl Filme- als auch Serien-Suche laufen einwandfrei.

Vl. hat's bloß temporär bei trakt geklemmt? Die Lastship - Suche nutzt ja quasi trakt.tv

**Comment by lastship** [comment]
Er hat hier nicht dazu geschrieben,dass er Kodi18 benutzt.Lastship Suche läuft nur unter Kodi18Alpha so einiger maßen.Anpassung an Kodi18 erfolgt erst mit Kodi18 Final Version

**Comment by lybserv** [comment]
Sorry, hätte ich erwähnen sollen..

Ja, lag nur an Kodi 18 - bin jetzt vorerst zurück auf 17 und muss wohl ohne Netflix und Co. leben...
Suche funktioniert einwandfrei dort, kann also geclosed werden hier ;-) 

Danke!
