### ISSUE TITLE
Serienstream funktioniert nicht mehr

### ISSUE THREAD

**Issue by MartinX3** [lastship/plugin.video.lastship#220]
Schlagartig funktioniert SerienStream trotz Account nicht mehr.
Entweder springt KODi beim Auswahl des Eintrags einfach weiter oder merkt an, dass dies ein geschützter Link sei, der einen Account erfordert.

Ich kann mich auf deren Website mit meinem Account anmelden und ihn regulär nutzen.

Und danke für eure tolle Arbeit!

**Comment by lastship** [comment]
Danke. Bitte beobachten, denn es ist schon oft so gewesen, dass Dein problem auftrat und dann nach ein paar Versuchen hat es wieder ohne Probleme funktioniert
Eventuell mal Kodi neu starten und Cache leeren

**Comment by MartinX3** [comment]
"denn es ist schon oft so gewesen, dass Dein problem auftrat"
Klingt nicht gerade nett.
Das "oft" stimmt auch nicht.
Wie viele Bug Tickets habe ich denn schon geschrieben, mit Kram den ich kaputt gemacht haben soll?
Und ich habe mich auch noch für eure Arbeit bedankt...

Außerdem, dieser Fehler passiert auf mehreren Endgeräten.
Linux Ubuntu, MacOS, Android und auf RaspianOS.

Bitte sei in Zukunft konstruktiv, ohne unhöfliche Zwischenkommentare zu verfassen. 
Ich möchte eine neutrale bzw freundlichen Umgang, sonst spare ich mir auch meine Höflichkeit.

**Comment by noahf1** [comment]
Ich glaube das hast du ein bisschen falsch interpretiert. Niemand wollte dich angegriffen. Es ging ledeglich allgemein um das SerienStream Problem ("Dein Problem" = Problem, dass du in diesem issue beschrieben hast) und nicht um Probleme, die du bereits reported hast.

**Comment by Erestris** [comment]
> Ich mag es, wenn Menschen ehrenamtlich nett zueinander sind und sich helfen.
> Open Source mag ich als Entwickler und Endanweder sowieso.

Magst du dann vielleicht uns helfen? Wir haben zu wenig Entwickler.... und bzgl. Kodi 18 machen ein paar Sachen noch Probleme.
Würde uns freuen einen mehr zu haben :-)

Am besten schaust du mal zu uns ins Forum: 
https://www.lastship.square7.ch/home/forum/

**Comment by Erestris** [comment]
Sehr schön :-)
Ich bin mir sicher du wirst was finden wo du helfen kannst :-)

**Comment by MartinX3** [comment]
Ich hab mich mal im Forum vorgestellt und meine Hilfe angeboten. :)
Jemand wird mir sicher noch antworten. :D


Jetzt ist nur noch die Frage offen, wie ich dieses Problem "debuggen" kann.
Oder sollte ich weiter warten?

**Comment by MartinX3** [comment]
Das Problem ist bei mir leider immer noch offen.

Ich habe die Funktion "alle Caches leeren" genutzt, KODi neugestartet, die Accountdaten neu eingetragen und er meckert die ganze Zeit, dass das ein geschützter Link sei und ich einen Account hinterlegen müsste.

**Comment by Erestris** [comment]
Hey,

in der aktuellen Nightly steht unter den Accountdaten ein Hinweistext um dass zu erklären.

Das ganze liegt an s.to und tritt häufig auf wenn schnell auf Streams von Ihnen zugegriffen wird. Diese Sperre verschwindet nach einiger Zeit wieder. 

Wir können da leider erst einmal so nichts machen.

**Comment by MartinX3** [comment]
Vielen Dank für den Hinweis.
Dann muss ich zum einen nur darauf warten, dass die Sperre nach über 2 Wochen endlich verschwindet (hatte das Problem schon einige Zeit, bevor ich diesen Issue  angelegt habe)
zum anderen, dass meine Stable Version endlich um den Hinweis aktualisiert wird. :)

**Comment by Erestris** [comment]
Dann ist das sehr seltsam und dann kann das erwähnte nicht die Ursache sein... die Sperre dauert evtl ne Stunde oder so.

Hmmm erstell bitte um Forum einen Bugreport mit Log.

**Comment by MartinX3** [comment]
Gerne. Gibt es ein FAQ zum Loggin?

**Comment by Erestris** [comment]
Zum Login bei s.to? Nein nicht wirklich. Ich kann mir momentan auch noch nicht erklären wieso du durchgehend dieses Problem hast. So sollte es definitiv nicht sein und mir ist kein vergleichbarer Fall bekannt. Hoffe dass einer der Entwickler helfen kann.

**Comment by MartinX3** [comment]
Seltsam, jetzt klappt es wieder auf allen Geräten.
Ggf doch eine Sperre?

Und sorry, leider fehlte mir die Zeit ein Log zu erstellen.
Aber das hat sich ja zum Glück erledigt.
