### ISSUE TITLE
trakt.py Zeile 144

### ISSUE THREAD

**Issue by Erestris** [lastship/plugin.video.lastship#221]
Zeile 144 sollte in der settings.xml bei trakt.user (Zeile 118) den Wert bei default auf den Benutzernamen setzen. Dies ist in Kodi 18 Beta 5 nicht mehr der Fall.

**Comment by lastship** [comment]
Ja leider ist es so, dass mit Kodi18, nach erflogreicher Trak Authorisierung, der Trakt Benutzer nicht angezeigt wir. Die Verbindung ist aber korrekt hergestellt
https://www.lastship.ch/Bugtracker/index.php?issue/74-gesehenstatus-wird-nicht-angezeigt-nach-episode/&commentID=469#comment469

**Comment by Philps** [comment]
in trakt.py ist alles iO das problem ist in den settings zu suchen.

es wird lediglich "open_trakt_auth" angezeigt, dies ist eine action zum authentifizieren.
id=trakt.user gibt es 2x mal. setzt man beide auf visible, sieht man auch das Feld Bentutzer.

Das Ziel sollte, sein "open_trakt_auth" den benutzer mitzugeben oder aber das Benutzer Feld lediglich zu listen und "Berechtigung" in Trakt Authentifizierung durchführen" oä. ändern und dabei nur 1 trakt.user feld in den settings zu lassen und dieses auf visible zu stellen

**Comment by Erestris** [comment]
Erledigt.
