### ISSUE TITLE
Netflix keine Serien

### ISSUE THREAD

**Issue by lastship** [lastship/plugin.video.lastship#240]
Es ist nicht möglich, dass Serien von Netflix bei den Suchergebnissen angezeigt werden
Das Problem. 
- es werden nicht mehr die richtigen Cookies gezogen, 
Die Session Cookies für Netflix sind mehr als dürftig,daher geht der Call in ein 401 ( Not authorized )

Filme werden angezeigt

**Comment by ruegnueg** [comment]
Noch ein Grund netflix, obwohl es nur 3 Euro sind, zu kicken.

**Comment by lastship** [comment]
Eine Möglichkeit wäre den Scraper anzupassen, so dass die Benutzerdaten von Netflix direkt in Lastship eingetragen werden können.Dann sollten auch Serien wieder funktionieren

**Comment by Philps** [comment]
es gibt 3rd party APIs https://blog.rapidapi.com/directory/netflix/

**Comment by wintuxx** [comment]
Oder könnte man die Suchanfragen über das Netflix Addon laufen  und dann über Lastship auswerten lassen?

**Comment by ruegnueg** [comment]
Filme werden angezeigt?
Bei mir jedenfalls sehr selten, obwohl definitiv vorhanden.

**Comment by wintuxx** [comment]
kann geschlossen werden.

gelöst mit #279

**Comment by lastship** [comment]
Gelöst mit 3.0.10~nightly7
