### ISSUE TITLE
Verzeichnis Kinos öffnet nicht bei nightly 17 3.0.2.8 & 3.0.2.7

### ISSUE THREAD

**Issue by Belvederr** [lastship/plugin.video.lastship#245]
Hallo Team LS

Zurzeit öffnet sich bei verzeichnis -in den Kinos- nicht und bei manchen kommen Bollywood Filme wenn sie drauf klicken. Kann man was tun oder muss man abwarten ?

danke im voraus für eine Antwort.

**Comment by Erestris** [comment]
Aktuelle Nightly installieren. Es funktioniert. Auch der verwendete Link wirft korrekte Ergebnisse aus.

**Comment by Belvederr** [comment]
Auf Vavoo 1.51 lässt sich der Plugin Nightly 17 nichtmal installieren kommt fehler Meldung.

Trotzdem danke warte mal ab was bei.der Version 3.0.2.7 passiert

**Comment by Belvederr** [comment]
Ich bedanke mich für eure Antwort & Zeit.
