### ISSUE TITLE
Suche zählt nich ganz herunter & bei inaktiven Links verschwindet das Popup Menü

### ISSUE THREAD

**Issue by DanielKoenigCoder** [lastship/plugin.video.lastship#255]
edit 2: Auch bei 3.0.8 nightly 1 treten die Probleme auf

edit: Auch bei 3.0.7 treten beide Probleme weiterhin auf

1. Beim Suchen aktualisiert sich das Popup Menü nach einer Zeit nicht mehr.
Es sind z. B. noch 9 Indexseiten verbleibend. Der Progress in Prozent läuft weiter auf 100%, aber die Indexseiten werden nicht weiter durchsucht oder es wird zumindest nicht weiter angezeigt.

https://www.lastship.ch/Bugtracker/index.php?issue/66-indexseiten-z%C3%A4hlen-nicht-mehr-komplett-runter/#comment411

2. In der Ergebnisseite verschwindet das Popup Fenster, sobald 1 Link nicht online ist.
Man denkt zuerst, es passiere nichts weiter. Doch dann öffnet sich z. B. ein Fenster, dass man sich für einen Hoster freischalten soll. Die Popup Fenster, welche dazwischen eigentlich auftauchen sollten (bzw. das durchlaufen der einzelnen Hoster/Links) ist aber nicht zu sehen.

Kodi 18 x64 mit Standardskin
Windows 10 1803 x64

Logfile sagt folgendes

```
11:53:54.984 T:2120  NOTICE: URLResolver: Initializing URLResolver version: 5.0.20

11:53:55.025 T:2120 WARNING: CAddonSettings[plugin.video.lastship]: cannot reference setting (relative index: -23; absolute index: -11) in another category in old setting condition "!eq(-23,)" for "prgr.sortorder"

11:53:55.025 T:2120 WARNING: CAddonSettings[plugin.video.lastship]: failed to parse visible condition "!eq(-23,)" of old setting definition for "prgr.sortorder"

11:53:55.776 T:2120   ERROR: Window Translator: Can't find window popuprecapinfowindow

11:53:55.945 T:3108   ERROR: XFILE::CDirectory::GetDirectory - Error getting resources/skins/Default

11:53:55.958 T:3108   ERROR: EXCEPTION: XML File for Window is missing

11:53:55.988 T:8924 WARNING: Skin has invalid include: VisibleFadeEffect

11:53:56.293 T:2120   ERROR: Window Translator: Can't find window popuprecapinfowindow

11:54:37.112 T:2316   ERROR: Previous line repeats 1 times.
```

**Comment by lastship** [comment]
Zu Punkt 1:

Diesen Fehler tritt vermehrt auf und einige User Berichten davon
Im Selbststest konnte das Problem nachgestellt werden

Ursache muss noch gesucht werden

zu punkt 2: Keine Ahnung was damit genau gemeint ist

**Comment by DanielKoenigCoder** [comment]
Zu Punkt 2:

Normalerweise bleibt (wie bei eigentlich all diesen Exodus Forks) nach dem auswählen eines Links das Popup Fenster offen, wenn ein Link offline ist. Man sieht dann, wie nach und nach die weiteren Links in der Liste "durchgegangen" werden (Erst Nr 1, dann Nr 2, und so weiter...). Das passiert jedoch bei mir nicht.

Ist Link Nr 1 z. B. offline, dann verschwindet das Popup Fenster einfach. Man denkt, es hätte abgebrochen und würde nicht weiter versuchen die anderen Links "abzugrasen".
Doch im Hintergrund geht es trotzdem weiter. Man sieht halt nur nicht das passende Fenster.
Es öffnet sich dann auf einmal aus dem Nichts ein Stream oder es kommt halt ein Popup, in dem man sich für Openload oder andere Hoster freischalten soll.

**Comment by lastship** [comment]
Kannst du bitte eine Serie oder Film zum Testen anführen

**Comment by DanielKoenigCoder** [comment]
Mhh habs jetzt gerade noch mal probiert mit der neusten Nightly und es tritt nicht mehr auf.
Vielleicht lags doch irgendwo an meinem System, sorry :/

**Comment by lastship** [comment]
also bleibt nur noch punkt 1?

**Comment by lastship** [comment]
zu Punkt 1:

mit maximaler suchzeit (60s)sieht es so aus: Es wird  von  21 (je nach dem wieviele seiten man aktiviert hat) bis 8 als "Zahl" herunter gezählt und ab da werden dann die Indexseiten aufgezählt und nach und nach "ausgeblendet", bis alle durch sind

Ist also kein Fehler/Bug
