### ISSUE TITLE
Darsteller Suche mit "schnelle Suche" wird abgebrochen ohne Meldung und Anzeige

### ISSUE THREAD

**Issue by lastship** [lastship/plugin.video.lastship#257]
Seit einiger Zeit geht die Suche nach Schauspielern nicht mehr wenn die "Schnelle Suche" verwendet wird. Egal ob Film oder Serien

Ablauf: Schnelle Suche in Lastship eingeshellt

Suche---->Suche nach Darsteller/Serie/Film man gibt einen Namen ein, das Rad dreht sich kurz, danach passiert nichts mehr.

Auf 2 System, mit der aktuellen Kodi Version getestet.

Die normale Suche funktioniert dagegen OHNE dieses Problem

https://www.lastship.ch/Bugtracker/index.php?issue/70-darsteller-suche-in-lastship/

**Comment by noahf1** [comment]
Ist gefixt: 7d52ea386de0e48aea57269776840ab866b89b57
