### ISSUE TITLE
zum Teil fehlen Artworks (Cover)

### ISSUE THREAD

**Issue by lastship** [lastship/plugin.video.lastship#258]
User berichten, dass vereinzelt keinen Artworks zu Filmen/ Serien angezeigt werden
Vermehrt tritt dies mit Kod18 auf

Das kann passieren wenn z.B. über40 Filme in einer Liste angezeigt werden
Manchmal ist auch der Skin schuld

Normalerweise hilft es im userdata ordner die texture13.db und den thumbnails ordner zu löschen

Wenn man bestimmte Titel sucht, dann werden selbst hier keine Cover angezeigt, ebenso wie im widget oder überall. Andere bilder werden jedoch angezeigt zum Titel.

ins log schauen ob ihr tmdb fehler bekommt. Es wird dann auf fanart.tv ausgewichen
Die haben nicht alle cover

Und wenn einmal ein nicht vorhandenes cover im cache ist, bekommst halt für den titel nirgends ein Cover.....daher Cache leeren veruschen

**Comment by Animizio** [comment]
Mit der Anleitung oben lassen sich alle Fehler beheben. Manchmal ist es notwendig, den Cache zu löschen, Kodi neuzustarten und anschließend nochmal den Cache zu leeren. Spätestens dann sollten alle Fehler behoben sein, oder es wird ein neuer API Key benötigt.
