### ISSUE TITLE
Ansicht wird verändert ab der 2.Seite

### ISSUE THREAD

**Issue by lastship** [lastship/plugin.video.lastship#259]
Wenn man auf die 2. Seite z.b. bei "Neue Filme" geht, ändert Lastship die eingestellte Ansicht wieder auf Liste.

Das passiert auch bei Serien oder Genre  und allen anderen Kategorien, immer wenn es auf die 2. Seite (und Folgeseiten natütrlich auch) geht stellt  es um auf Listenansicht.

Einstellungen welche zuvor bei "Angezeigte Typen" eingestellt wurden, werden also ab Seite 2 nicht mehr korrekt angezeigt

Da das gleiche Verhalten auch bei AmazonVOD, Netflix usw. auftritt, wir es wohl an Kodi liegen

ABER wenn man bei Amazon auf manuelle view umstellt und dann die view Id vom skin eingibt, merkt sich der skin das auch für die folgeseiten

Ebenso beim netflix addon

Nur bei Lastship funktioniert das nicht auf den folgeseiten, warum auch immer ( möglicher Fehler beim erstellen der view.db????)
Aber in der view.db von lastship wird die view ID vom Skin richtig gespeichert

Hier mal die view ID's vom Estuary Standard Skin:

<include>View_50_List</include>

<include>View_51_Poster</include>

<include>View_52_IconWall</include>

<include>View_53_Shift</include>

<include>View_54_InfoWall</include>

<include>View_55_WideList</include>

<include>View_500_Wall</include>

<include>View_501_Banner</include>

<include>View_502_FanArt</include>

https://www.lastship.ch/Bugtracker/index.php?issue/41-ansicht-wird-ver%C3%A4ndert-bei-2-seite/

**Comment by Philps** [comment]
Amazon:
xbmc.executebuiltin('Container.SetViewMode(%s)' % viewid)

LastShip:
control.execute('Container.SetViewMode(%s)' % str(view))

Es wird bei jeden directory listing der befehl aufgerufen mit den korrekt gesetzen ViewID. Fraglich ob ein Containe Refresh oder Container update fehlt.

**Comment by lastship** [comment]
Gelöst mit 3.0.10~nightly12
