### ISSUE TITLE
Neue Folgen in der Bibliothek obwohl Streams nur Englisch

### ISSUE THREAD

**Issue by macross5** [lastship/plugin.video.lastship#272]
Hallo zusammen,

ich weiß nicht ob dies ein Fehler ist oder beabsichtigt. 
Ich habe eingestellt, dass vor der Bibliothekanlage, die Streams überprüft werden sollen. Bei der Wiedergabe habe ich eingestellt, dass Serien mit dem Tag Subbed gefiltert werden. Nichtsdestotrotz finde ich Staffeln in der Bibliothek, welche keinen deutschen Stream besitzen. 
Prüft die Anlage in die Bibliothek nicht sie Filterung? Falls nein, kann dies zukünftig ggf. programmiert werden oder mir gesagt werden, wo ich welche Anpassung im Code vornehmen muss?

Vielen Dank!

**Comment by Erestris** [comment]
Es ist korrekt dass die Bibliotheksimportierung dies nicht prüft. Diese prüft nur ob die Daten der Serie / des Filmes vorhanden sind und fügt diese dann hinzu.
Damit diese das filtern könnte müsste sie für jede Episode / jeden Film versuchen Streams zu finden.... was in einem riesigen Berg an Anfragen bei den Hostern enden würde für die Bibliotheksimportierung.
Die besagte Option für „subbed“ ist nur eine Filterung der Ergebnisse die dir angezeigt werden bei Hostern (also nachträglich nachdem alle Stream-Links gefunden wurden).

Eine Option wie du sie gerne hättest würde, wie bereits gesagt, sehr viele Anfragen notwendig machen (wodurch die Seiten irgendwann dicht machen werden) und außerdem sehr viel Rechenleistung verschlingen und ziemlich lange dauern.

Wird es so also nicht geben.

**Comment by macross5** [comment]
Vielen Dank für deine Antwort. Kann ich komplett nachvollziehen.

Gibt es denn einen Release Kalender wo die deutschen Folgen beim Erscheinen hinterlegt werden?

**Comment by Erestris** [comment]
Ein direkter Releasekalender ist mir leider nicht bekannt. Fernsehserien.de ist recht zuverlässig.

**Comment by Erestris** [comment]
Kann geschlossen werden.
