### ISSUE TITLE
Keine Titel in der Bibliothek bei Serien

### ISSUE THREAD

**Issue by Numbers11** [lastship/plugin.video.lastship#288]
Kodi 17

Bin mir nicht komplett sicher, ob das ein Problem mit dem Addon ist, aber wenn ich eine Serie versuche zur Bibliothek hinzuzufügen, wird nur der Serieneintrag selbst hinzugefügt, nicht aber die Staffeln oder Episoden.

In addon_data\plugin.video.lastship sehe ich aber die korrekt aussehende Ordnerstruktur mit NFO-Datei und STRM-Dateien.

Bspw. für True Detective:

True Detective (2014)
- Season 1
-- True.Detective.S01E01.strm -> "plugin://plugin.video.lastship/?action=play&title=Die+lange+strahlende+Dunkelheit&year=2014&imdb=tt2356777&tvdb=270633&season=1&episode=1&tvshowtitle=True+Detective&date=2014-01-12"
-- ...
- Season 2
- Season 3
- tvshow.nfo -> "http://thetvdb.com/?tab=series&id=270633"

Ich habe den TVShows-Ordner nach dieser Anleitung hinzugefügt: https://www.kodi-tipps.de/lastship-streams-in-kodi-bibliothek-einbinden/

Also "Medium wechseln" -> "Videos", "Inhalt festlegen" -> "Serien"

**Comment by Erestris** [comment]
Es werden also keine .strm angelegt? Oder Kodi zeigt dir nur keine Titel an?

Am besten ist es nebenbei wenn du dir Hilfe nur bei uns im Forum (www.lastship.ch) holst und nicht irgendwelche Tutorials von Fremdseiten.

**Comment by Erestris** [comment]
Ah... Mist überlesen.... ja du hast die .strm. Aber du musst ja beim hinzufügen der Quellen angeben wie die gescrapt werden sollen (also wie kodi die Infos holen soll). Am besten googelst du einfach mal Scraper und Kodi. Oder du kommst zu uns ins Forum.

**Comment by Numbers11** [comment]
Vielen Dank  für die schnelle Antwort.
Das Problem lag in der Tat im Scraper, anscheinend hat sich die TheTVDB-Api geändert.
Mit dem TMDB-Scraper gibt es keine Probleme.
