### ISSUE TITLE
Netflix Serien und Filme werden nicht angezeigt

### ISSUE THREAD

**Issue by wintuxx** [lastship/plugin.video.lastship#289]
Und wieder funktioniert Netflix nicht mehr.
Bzw. In den suchergebnis wird kein Netflix link angezeigt.

Zwei Filme birdbox und cargo hab ich probiert, kein Netflix link.
Serien 
CastlevAnia Staffel 2 Folge 1
Designated Survivor S01E01
Auch ohne link

Hier der debuglog
http://paste.ubuntu.com/p/Xv3hK7W5DT

**Comment by Space2Walker** [comment]
Also ich finde mit der neuesten nightly **alle**. Hatte da aber auch noch mal was geändert, also am besten mal mit der nightly 23 testen.

**Comment by wintuxx** [comment]
Werde ich gleich, wenn ich Zuhause bin testen

**Comment by wintuxx** [comment]
Ja klappt wieder
