### ISSUE TITLE
Bei Seriestream und Bs.to funktioniert kein Stream 

### ISSUE THREAD

**Issue by MWild67** [lastship/plugin.video.lastship#4]
Setup: Raspi 3b, Latest LibreElec, Kodi 18.5, LastShip nightly

Ich habe gemäss Anleitung für Seriestream einen Account erstellt und diesen auch in den LastShip seetings eingetragen. 
Dito für BS.TO einen MyJDownloader Account erstellt und auch diesen eingetragen.

Das Resultat ist aber leider unverändert:
Seriestream kommt gar nicht bei den verfügbaren Hostern. Natürlich hab ich geprüft, dass es den gewünschten Stream dort auch gibt.
Bei Bs.to kommen zwei der vier verfügbaren Streams, aber wenn ich diese starte, bekomme ich nur die Meldung kein Stream. Und auch hier habe ich natürlich die MyJDownloader-App am laufen, damit ich das Captcha lösen kann, aber es zeigt mir schon gar keinen laufenden Downloader an.

Was kann ich noch tun, damit das besser bzw. überhaupt funktioniert.

**Comment by DWH-WFC** [comment]
Die Captcha funktioniert nicht mehr serienstream sollte laufen

**Comment by wintuxx** [comment]
Serienstrean liefert trotz url änderung keine Ergebnisse auf mein windows test system

**Comment by MWild67** [comment]
Hab ich bei mir auch nochmals geprüft. Da kommt bei Serienstrean gar nichts.
