### ISSUE TITLE
Sprache für Trailer

### ISSUE THREAD

**Issue by Kr1ss-XD** [lastship/plugin.video.lastship#67]
## Expected Behavior / Erwartetes Verhalten :

Trailer in der Sprache der Benutzereinstellung für Provider suchen

## Actual Behavior / Tatsächliches Verhalten :

Trailer in deutsch werden gesucht

#### Hardware, Kodi Version, Lastship Version :
alle
#### Environment (additional Hardware, OS, ...) / Umgebung (zusätzl. Hardware, Betriebssystem, ...) :
alle

### **(Link to / Link zum) Debug-Logfile** :
 _entfällt_

**Comment by nokodemus** [comment]
A setting dependency sounds great. But i think there could be a problem with dependency of the set provider language, as you're able to set both, english and german.

Didn't you mean to make the trailer language dependent of the setting" information-language"?

Greets and keep up the great work :+1:
